# Generated by Django 4.2.7 on 2024-02-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('message', models.TextField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='youtube_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
